name: u3_tarea4

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.121.2/hugo_extended_0.121.2_Linux-64bit.tar.gz
          tar -xzf hugo_extended_0.121.2_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Build site
        run: make build

      - name: Package
        run: make package

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body_path: DEPLOY.md
          files: awesome-website.zip
